# Generated by Django 3.1.3 on 2021-02-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='mobile_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
