# Generated by Django 3.1.3 on 2021-02-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userdetail_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
