# Generated by Django 3.1.3 on 2021-02-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userdetail_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
