# Generated by Django 3.1.3 on 2021-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210210_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='mobile_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
