# Generated by Django 3.1.3 on 2021-02-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210210_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_image',
            field=models.ImageField(blank=True, default='profileDefault.jpg', null=True, upload_to=''),
        ),
    ]
