# Generated by Django 3.1.3 on 2021-02-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210211_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefferalOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reff_name', models.CharField(max_length=225, null=True)),
                ('reff_discount', models.IntegerField(null=True)),
                ('reff_price', models.IntegerField(null=True)),
                ('reffered_person_discount', models.IntegerField(null=True)),
                ('order_maximum', models.IntegerField(null=True)),
                ('reff_offer_type', models.CharField(max_length=225, null=True)),
                ('reff_status', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
