# Generated by Django 3.1.3 on 2021-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_refferaloffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='state',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='wallet',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
