# Generated by Django 3.1.3 on 2021-02-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='offer_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('offer_start', models.DateField(null=True)),
                ('offer_expiry', models.DateField(null=True)),
                ('discount_amount', models.FloatField(null=True)),
                ('offer_type', models.CharField(blank=True, max_length=40, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.productdetail')),
            ],
        ),
    ]
