# Generated by Django 3.1.3 on 2021-02-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cancelledorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('validity_start', models.DateField(blank=True, null=True)),
                ('validity_end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
