# Generated by Django 3.1.3 on 2021-02-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cancelledorder_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledorder',
            name='refund',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
